### ISSUE TITLE
Pwn: Overflow1

### ISSUE THREAD

**Issue by marius-j-i** [Loevland/ctf-workshop#17]
@Loevland 
Får ikke gjort `gcc vuln.c` fordi C11 fjærna `gets` fra stdlib.
Vet du av nån bibliotek eller flag som en work around?

**Comment by marius-j-i** [comment]
Lol, nvm det va warning som så ut som error.
Funke fortsatt.

**Comment by Loevland** [comment]
Hvis gets() e fjerna kan den byttes ut me enten scanf(), fgets() eller read()

**Comment by Loevland** [comment]
Ah da så👌🏻👌🏻
